/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as ApiPublicBaselineOpportunityRouteImport } from './routes/api/public/baseline-opportunity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBaselineOpportunityRoute =
  ApiPublicBaselineOpportunityRouteImport.update({
    id: '/api/public/baseline-opportunity',
    path: '/api/public/baseline-opportunity',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/targets': typeof TargetsRoute
  '/api/public/baseline-opportunity': typeof ApiPublicBaselineOpportunityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/targets': typeof TargetsRoute
  '/api/public/baseline-opportunity': typeof ApiPublicBaselineOpportunityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/targets': typeof TargetsRoute
  '/api/public/baseline-opportunity': typeof ApiPublicBaselineOpportunityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/targets' | '/api/public/baseline-opportunity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/targets' | '/api/public/baseline-opportunity'
  id:
    '__root__' | '/' | '/docs' | '/targets' | '/api/public/baseline-opportunity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  TargetsRoute: typeof TargetsRoute
  ApiPublicBaselineOpportunityRoute: typeof ApiPublicBaselineOpportunityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/baseline-opportunity': {
      id: '/api/public/baseline-opportunity'
      path: '/api/public/baseline-opportunity'
      fullPath: '/api/public/baseline-opportunity'
      preLoaderRoute: typeof ApiPublicBaselineOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  TargetsRoute: TargetsRoute,
  ApiPublicBaselineOpportunityRoute: ApiPublicBaselineOpportunityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
